client_id = "ca9c0313d6836b7913180eb9bc16e082"
name = "post-purchase-ui"
application_url = "https://post-purchase-ui.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [ "https://post-purchase-ui.vercel.app/api/auth" ]
